# Generated by Django 5.0.4 on 2024-04-22 22:36

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CPU',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
                ('num', models.CharField(max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='Disc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('memory_standard', models.CharField(max_length=8)),
                ('size', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=20)),
                ('wilaya', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Ram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('memory_standard', models.CharField(max_length=8)),
                ('size', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Laptop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=20)),
                ('price', models.IntegerField()),
                ('has_delivery', models.BooleanField()),
                ('medias', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=10), size=5)),
                ('cpu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.cpu')),
                ('disk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.disc')),
                ('ram', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.ram')),
            ],
        ),
        migrations.CreateModel(
            name='announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField()),
                ('laptop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.laptop')),
            ],
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('slug', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=30)),
                ('image_url', models.CharField(max_length=30)),
                ('url', models.CharField(max_length=30)),
                ('followers', models.IntegerField()),
                ('annoncement_count', models.IntegerField()),
                ('locations', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.location')),
            ],
        ),
    ]
