# Generated by Django 5.0.4 on 2024-04-22 23:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='disc',
            old_name='memory_standard',
            new_name='tech_type',
        ),
        migrations.AddField(
            model_name='announcement',
            name='store',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.store'),
        ),
    ]
