# Generated by Django 5.0.4 on 2024-04-23 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_memory_standard_disc_tech_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cpu',
            name='brand',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
